import uinput
import string

UINPUT_TRANSLATE = {
    'a': uinput.KEY_A,
    'b': uinput.KEY_B,
    'c': uinput.KEY_C,
    'd': uinput.KEY_D,
    'e': uinput.KEY_E,
    'f': uinput.KEY_F,
    'g': uinput.KEY_G,
    'h': uinput.KEY_H,
    'i': uinput.KEY_I,
    'j': uinput.KEY_J,
    'k': uinput.KEY_K,
    'l': uinput.KEY_L,
    'm': uinput.KEY_M,
    'n': uinput.KEY_N,
    'o': uinput.KEY_O,
    'p': uinput.KEY_P,
    'q': uinput.KEY_Q,
    'r': uinput.KEY_R,
    's': uinput.KEY_S,
    't': uinput.KEY_T,
    'u': uinput.KEY_U,
    'v': uinput.KEY_V,
    'w': uinput.KEY_W,
    'x': uinput.KEY_X,
    'y': uinput.KEY_Y,
    'z': uinput.KEY_Z,
    'A': (uinput.KEY_A, uinput.KEY_LEFTSHIFT),
    'B': (uinput.KEY_B, uinput.KEY_LEFTSHIFT),
    'C': (uinput.KEY_C, uinput.KEY_LEFTSHIFT),
    'D': (uinput.KEY_D, uinput.KEY_LEFTSHIFT),
    'E': (uinput.KEY_E, uinput.KEY_LEFTSHIFT),
    'F': (uinput.KEY_F, uinput.KEY_LEFTSHIFT),
    'G': (uinput.KEY_G, uinput.KEY_LEFTSHIFT),
    'H': (uinput.KEY_H, uinput.KEY_LEFTSHIFT),
    'I': (uinput.KEY_I, uinput.KEY_LEFTSHIFT),
    'J': (uinput.KEY_J, uinput.KEY_LEFTSHIFT),
    'K': (uinput.KEY_K, uinput.KEY_LEFTSHIFT),
    'L': (uinput.KEY_L, uinput.KEY_LEFTSHIFT),
    'M': (uinput.KEY_M, uinput.KEY_LEFTSHIFT),
    'N': (uinput.KEY_N, uinput.KEY_LEFTSHIFT),
    'O': (uinput.KEY_O, uinput.KEY_LEFTSHIFT),
    'P': (uinput.KEY_P, uinput.KEY_LEFTSHIFT),
    'Q': (uinput.KEY_Q, uinput.KEY_LEFTSHIFT),
    'R': (uinput.KEY_R, uinput.KEY_LEFTSHIFT),
    'S': (uinput.KEY_S, uinput.KEY_LEFTSHIFT),
    'T': (uinput.KEY_T, uinput.KEY_LEFTSHIFT),
    'U': (uinput.KEY_U, uinput.KEY_LEFTSHIFT),
    'V': (uinput.KEY_V, uinput.KEY_LEFTSHIFT),
    'W': (uinput.KEY_W, uinput.KEY_LEFTSHIFT),
    'X': (uinput.KEY_X, uinput.KEY_LEFTSHIFT),
    'Y': (uinput.KEY_Y, uinput.KEY_LEFTSHIFT),
    'Z': (uinput.KEY_Z, uinput.KEY_LEFTSHIFT),
    '0': uinput.KEY_0,
    '1': uinput.KEY_1,
    '2': uinput.KEY_2,
    '3': uinput.KEY_3,
    '4': uinput.KEY_4,
    '5': uinput.KEY_5,
    '6': uinput.KEY_6,
    '7': uinput.KEY_7,
    '8': uinput.KEY_8,
    '9': uinput.KEY_9,
    ')': (uinput.KEY_0, uinput.KEY_LEFTSHIFT),
    '!': (uinput.KEY_1, uinput.KEY_LEFTSHIFT),
    '@': (uinput.KEY_2, uinput.KEY_LEFTSHIFT),
    '#': (uinput.KEY_3, uinput.KEY_LEFTSHIFT),
    '$': (uinput.KEY_4, uinput.KEY_LEFTSHIFT),
    '%': (uinput.KEY_5, uinput.KEY_LEFTSHIFT),
    '^': (uinput.KEY_6, uinput.KEY_LEFTSHIFT),
    '&': (uinput.KEY_7, uinput.KEY_LEFTSHIFT),
    '*': (uinput.KEY_8, uinput.KEY_LEFTSHIFT),
    '(': (uinput.KEY_9, uinput.KEY_LEFTSHIFT),
    ' ': uinput.KEY_SPACE,
    '[': uinput.KEY_LEFTBRACE,
    '{': (uinput.KEY_LEFTBRACE, uinput.KEY_LEFTSHIFT),
    ']': uinput.KEY_RIGHTBRACE,
    '}': (uinput.KEY_RIGHTBRACE, uinput.KEY_LEFTSHIFT),
    '`': uinput.KEY_GRAVE,
    '~': (uinput.KEY_GRAVE, uinput.KEY_LEFTSHIFT),
    '/': uinput.KEY_FORWARD,

    '_entr': uinput.KEY_ENTER,
    '_left': uinput.KEY_LEFT,
    '_rght': uinput.KEY_RIGHT,
    '_up': uinput.KEY_UP,
    '_down': uinput.KEY_DOWN,
    '_home': uinput.KEY_HOME,
    '_end': uinput.KEY_END,
    '_bksp': uinput.KEY_BACKSPACE,
    '_tab': uinput.KEY_TAB,
    '_ctrl': uinput.KEY_LEFTCTRL,

    '_mbt1': uinput.BTN_LEFT,
    '_mbt2': uinput.BTN_RIGHT,
    '_mbt3': uinput.BTN_MIDDLE,
    '_scup': uinput.KEY_SCROLLUP,
    '_scdn': uinput.KEY_SCROLLDOWN
}

OTHERS = ( uinput.REL_X,
           uinput.REL_Y )
UINPUT_ACTIVATE = set()
for val in UINPUT_TRANSLATE.values():
    if isinstance(val[0], (list, tuple)):
        UINPUT_ACTIVATE.update(val)
    else:
        UINPUT_ACTIVATE.add(val)
UINPUT_ACTIVATE.update(OTHERS)

UINPUT_ACTIVATE = list(UINPUT_ACTIVATE)
